cors:
  originPatterns: http://localhost:5500,http://localhost:3000,https://spc-azure.vercel.app
spring:
  jackson:
    time-zone: America/Sao_Paulo
  application:
    name: spc
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${{MySQL.MYSQLHOST}}:${{MySQL.MYSQLPORT}}/${{MySQL.MYSQLDATABASE}}?useSSL=false&allowPublicKeyRetrieval=true&useTimezone=true&serverTimezone=America/Sao_Paulo
    username: ${{MySQL.MYSQLUSER}}
    password: ${{MySQL.MYSQLPASSWORD}}
  profiles:
    active: prod
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
    show-sql: false
    open-in-view: false