INSERT INTO `etapa` VALUES
(1,'PRIMEIRA_ETAPA','SAO_SEBASTIAO'),
(2,'PRIMEIRA_ETAPA','SAO_SEBASTIAO'),
(3,'SEGUNDA_ETAPA','SAO_SEBASTIAO'),
(4,'EUCARISTIA_UM','SAO_SEBASTIAO'),
(5,'EUCARISTIA_DOIS','SAO_SEBASTIAO'),
(6,'PRE_CRISMA','SAO_SEBASTIAO'),
(7,'CRISMA','SAO_SEBASTIAO'),
(8,'CRISMA','SAO_SEBASTIAO'),
(9,'CRISMA','SAO_SEBASTIAO'),
(10,'CRISMA','SAO_SEBASTIAO'),
(11,'EUCARISTIA_UM','DIVINO_ESPIRITO_SANTO'),
(12,'CRISMA','DIVINO_ESPIRITO_SANTO');